overrides:
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  qs@<6.14.1: '>=6.14.1'
